- README.md
Update "how to run" instructions to use the `build --serve` command with mastarm.
This is how I was able to get scenario-editor to build/run anyway. I might just be using mastarm incorrectly...?  Came across this while working in #126.
> docs(README): Update mastarm usage.

- lib/map/scenario-map.js
- lib/scenario-editor.js
Use react-redux's `connect` function to make `ScenarioMap` a "smart" component. Reduces coupling
between `ScenarioEditor` and `ScenarioMap`. Work in progress towards issue #122.
I didn't have any "real" data to test the changes with, but I did what I could put together some fake data to use for testing by examining your graphql query and `project-store`.
I tried to match your style and conventions as closely as I could, but if there are any issues I'd be happy to correct them.
(You might be wondering why a random person is sending in a PR - I came across Conveyal in a job listing for a javascript engineer position, and since your team has a bunch of code on github I thought I'd dig through it a little bit and get a feel for some of the projects you're working on. Interesting stuff!)
> refactor(scenario-map): Connect ScenarioMap directly to redux store.

- docs/edit-scenario.md
- lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
- lib/components/modification/__tests__/__snapshots__/editor.js.snap
- lib/components/modification/__tests__/__snapshots__/frequency-entry.js.snap
- lib/components/modification/__tests__/__snapshots__/timetable-entry.js.snap
- lib/components/modification/__tests__/__snapshots__/timetable.js.snap
- lib/components/modification/editor.js
- lib/components/modification/timetable-entry.js
- lib/utils/__tests__/timetable.js
- lib/utils/convert-to-r5-modification/add-trip-pattern.js
- lib/utils/convert-to-r5-modification/convert-to-frequency.js
- lib/utils/time.js
- lib/utils/timetable.js
Add ability to create routes that have exact times (i.e. they depart at exactly the given frequency from startTime inclusive to endTime exclusive, with no variation/Monte Carlo simulation). Should be ready to go.
> Exact times

- lib/utils/browsochrones.js
Previously we did not keep the cached profile request up to date as parameters changed, which meant
that, once any parameter that caused refetch had been changed, we were always refetching the origin
if any parameters changed, even if they were parameters that should not cause a refetch. e.g. you
could change the date and that would correctly cause a refetch, but after that changing the
isochrone cutoff would cause a refetch, which it shouldn't.
> fix(browsochrones): Don't refetch origin when changing isochrone cutoff.

- lib/components/modification/group.js
We have nicely formatted modification names in messages, this uses them rather than sentence-casing the type param. This also allows us to give more human readable names to the less obvious modification types (e.g. convert-to-frequency becomes adjust frequency).
> feat(modification-group): Use modification name from messages.

- configurations/default/messages.yml
- lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
- lib/components/modification/__tests__/__snapshots__/edit-alignment.js.snap
- lib/components/modification/__tests__/__snapshots__/editor.js.snap
- lib/components/modification/__tests__/__snapshots__/reroute.js.snap
- lib/components/modification/__tests__/edit-alignment.js
- lib/components/modification/add-trip-pattern.js
- lib/components/modification/edit-alignment.js
- lib/components/modification/reroute.js
- lib/components/scenario-map/index.js
- lib/constants/index.js
The form and functionality required to begin editing the alignments of Add Trips & Reroute modifications is almost identical and therefore an appropriate place to pull out into a common component.
> Pull out common code between Add Trips & Reroute.

- lib/components/modification/edit-alignment.js
We were using `mapState` to manage this so if you weren't currently editing the alignment, it wouldn't maintain the state when you checked/unchecked the box.
fixes #280
> Correctly set auto create stops on new modifications

- lib/actions/analysis/index.js
- lib/actions/index.js
- lib/actions/network.js
- lib/reducers/network.js
Allow calling lock ui with error with a string, an Error object, or { error, detailMessage } object.
Don't use createAction due to an upstream :ant: https://github.com/acdlite/redux-actions/issues/194
fixes #300
> fix(error): Fix lock UI with error.

- package.json
XorShift was being included transitively, which meant that when it was minified, the reference to it
became broken.
> fix(regional): Add direct dependency on xorshift package :package:

- package.json
- yarn.lock
The quantile scale does not work in Gridualizer 2.0.0 due to an import error with the constructor.
Ergo, install 2.0.1.
Fixes #328.
This is basically what is deployed to production, except that here I have updated package.json to require gridualizer ^2.0.1 whereas on production it grabbed 2.0.1 just because it's the latest 2.x release.
> fix(regional): bump gridualizer version so comparisons work :tools:

- lib/actions/__tests__/__snapshots__/project.js.snap
- lib/actions/project.js
- lib/containers/opportunity.js
- lib/reducers/analysis.js
Currently, the layer showing the grid on the map is added as soon as the results come back. However, this fails on the first request as the grid may not have been added to the state. This puts a default grid in the state so that rendering does not fail in the split-second before the correct grid is displayed.
> Don't require user to manually select a grid before results are shown

- lib/components/report/index.js
- lib/components/sidebar.js
Shows an alert in the Report view and the error icon in the normal application. Closes #429
> Catch and report errors and unhandled promise rejections

- configurations/default/messages.yml
- lib/components/create-grid.js
- lib/components/edit-scenario.js
- lib/styles.css
- package.json
Uses react-tooltip to add instructions about opportunity dataset and GTFS bundle upload.
Adds a ❔ to those panels. When users hover over ❔, a tooltip with abbreviated instructions appears. We could consider making the ❔s link to the appropriate readthedocs pages, but the maintenance required to update links as readthedocs changes might not be worth it.
> Explanatory tooltips (now on latest base branch)

- lib/utils/update-add-stops-terminus.js
We switched "Create Stops Automatically" to be off by default. With a default spacing in selected
segments for reroute modifications this caused a mismatch in what was presented vs assumed. This
commit sets the default stop spacing to be 0 to match.
closes #502
> Default to 0 stop spacing for segments

- configurations/default/messages.yml
- lib/components/__tests__/__snapshots__/edit-bundle.js.snap
- lib/components/__tests__/edit-bundle.js
- lib/components/edit-bundle.js
- lib/containers/edit-bundle.js
- lib/containers/scenario.js
This fixes the currently broken "edit bundle" form. Initial implementation took a different approach to display more information about the feed while editing.
> Simplify edit bundle and modify it to edit feed names

- lib/components/analysis/__tests__/__snapshots__/profile-request-editor.js.snap
- lib/components/analysis/egress-mode-selector.js
- lib/components/analysis/mode-selector.js
- lib/components/analysis/profile-request-editor.js
- lib/components/analysis/stacked-percentile-selector.js
- lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
- lib/styles.css
- lib/types.js
Users should be able to select between walking/bike for access/egress legs, and set speeds for these modes.  This PR adds related components to the front-end, but disables some of them until back-end issues are resolved.
> Add front-end options to set access/egress parameters

- configurations/default/messages.yml
- lib/components/__tests__/__snapshots__/edit-bundle.js.snap
- lib/components/edit-bundle.js
- lib/components/modification/remove-trips.js
- lib/containers/__tests__/__snapshots__/edit-bundle.js.snap
- lib/containers/__tests__/edit-bundle.js
- lib/containers/adjust-dwell-time.js
- lib/containers/convert-to-frequency.js
- lib/containers/remove-stops.js
- lib/containers/remove-trips.js
- lib/containers/reroute.js
- lib/reducers/__tests__/__snapshots__/scenario.js.snap
- lib/reducers/scenario.js
- lib/selectors/current-scenario-id.js
- lib/utils/mock-data.js
Fix mismatches when editing bundles and navigating to projects afterwards.
NOTE: This does not modify/fix how we name feeds (from the agency list) aka the Amtrak -> Martz Trailways problem that @ansoncfit noticed. I initially went down the path of updating that but due to discussions of possibly changing how we handle bundles/feeds in the future I didn't end up wanting to muck around with that too much. 
So you can just manually change it to the appropriate name for now 👍
> Fix and enable bundle editing

- configurations/default/messages.yml
- lib/components/__tests__/__snapshots__/edit-project.js.snap
- lib/components/__tests__/__snapshots__/edit-scenario.js.snap
- lib/components/__tests__/__snapshots__/r5-version.js.snap
- lib/components/edit-scenario.js
- lib/constants/analysis.js
Adds a strongly worded warning for projects set to use R5 < v3.1.0
The warning appears in the project selection and regional settings views.  It hasn't yet been added to the scenario editing or analysis views, but those tend not to be accessed directly.
> Outdated r5 warning

- configurations/default/messages.yml
- lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
- lib/components/modification/__tests__/__snapshots__/edit-alignment.js.snap
- lib/components/modification/__tests__/__snapshots__/reroute.js.snap
- lib/components/modification/add-trip-pattern.js
- lib/components/modification/adjust-speed.js
- lib/components/modification/edit-alignment.js
- lib/components/modification/reroute.js
- lib/components/scenario-map/index.js
- lib/containers/__tests__/__snapshots__/modification-editor.js.snap
- lib/utils/update-add-stops-terminus.js
This PR attempts to make reroute modifications more intuitive for users.  
1. From Stop and To Stop selection buttons are relabeled, clarifying that these are existing stops on the currently selected pattern.  
2. Edit alignment is disabled until fromStop or toStop has been selected
3. Users can now clear fromStop and toStop, and select different ones (resolving #105)
This is different approach than suggested in #104, but it may be usable enough to close that issue.
> Reroute modifications

- lib/components/modification/reroute.js
Small fixes for #578 
-If only "Start of reroute/extension" (`fromStop`) is set, `extendFromEnd` should be true.
-If only "End of reroute/extension" (`toStop`) is set, `extendFromEnd` should be false (because we want to extend backwards from the start of the reroute segment).
-If both are selected, `allowExtend` should be false.
> Reroute Fixes

- lib/components/modification/editor.js
- lib/components/modifications-map/index.js
- lib/constants/index.js
Similar to the fix in the modification editor, debounce updates to prevent nonce clashing.
> Debounce modification saving on the modification map

- lib/__tests__/__snapshots__/routes.js.snap
- lib/components/__tests__/select-region.js
- lib/components/region.js
- lib/components/select-region.js
- lib/containers/region.js
- lib/containers/select-region.js
We were reloading the region when switching to a project unnecessarily and it sometimes overwrote
the project bundle if the data came back in the wrong order. This commit only "unloads" the region
fully when switching to the region selector.
closes #591
> Reloading the regions incorrectly overwrote the bundles

- lib/components/modification/editor.js
- lib/constants/index.js
- lib/containers/__tests__/__snapshots__/modification-editor.js.snap
- lib/containers/__tests__/modification-editor.js
- lib/containers/modification-editor.js
Move from auto-saving on each change to only saving every ten seconds or on `componentWillUnmount` (when you leave editing the modification) and only when there have been changes. closes #589
The motivation for using this style as opposed to a save button is that it would be difficult to set route or pattern data without saving it because of the way we retrieve that data from the server.
> Switch modification saving style

- lib/actions/analysis/__tests__/__snapshots__/regional.js.snap
- lib/actions/analysis/__tests__/regional.js
- lib/actions/analysis/regional.js
- lib/components/analysis/__tests__/__snapshots__/regional.js.snap
- lib/components/analysis/__tests__/regional.js
- lib/components/analysis/index.js
- lib/components/analysis/regional-results.js
- lib/components/map/regional.js
- lib/containers/regional-analysis-results.js
- lib/modules/admin/utils.js
- lib/selectors/isochrone.js
- lib/selectors/nearest-percentile-index.js
- lib/types.js
By default, R5 no longer bootstraps estimates of accessibility, which obviates the probability masking features for regional analysis results.  This PR removes masking features and makes a few other small changes:
- Eliminates the fetch of the probability surface from analysis-backend, which was triggering an occasional bug.
- Eliminates the "minimum probability of change" slider
- Corrects cloudwatch logGroup used in link from admin panel
- Changes the default suggestion for regional analysis names (see discussion in #538).  While we're at it, we might also want to tackle #737.
- Refactors calculation of percentiles (steps toward #619, #756)
> Remove probability masking

- lib/actions/analysis/__tests__/__snapshots__/index.js.snap
- lib/actions/analysis/index.js
- lib/actions/region.js
- lib/components/analysis/index.js
- lib/modules/opportunity-datasets/components/selector.js
- lib/modules/r5-version/index.js
- lib/reducers/__tests__/__snapshots__/analysis.js.snap
- lib/reducers/__tests__/analysis.js
- lib/reducers/analysis.js
This PR fixes #744 and #710 by:
1. Loading Opportunity Datasets each time the selector is shown (on page navigation)
2. Loading Regional Analyses when navigating to the analysis page
3. Setting the entire profile request--instead of just updating it--on region change
> Set region data correctly

- configurations/default/messages.yml
- lib/actions/get-feeds-routes-and-stops.js
- lib/components/modification/editor.js
Undoes fix for #696
Adds note in UI that only one route will be shown on map, which we'll want to keep until some backend/gtfs-api changes.
> Show only one route per modification on map

- configurations/default/messages.yml
- lib/components/__tests__/__snapshots__/edit-bundle.js.snap
- lib/components/analysis/stacked-percentile-selector.js
- lib/components/create-bundle.js
- lib/components/edit-bundle.js
- lib/containers/__tests__/__snapshots__/edit-bundle.js.snap
- lib/selectors/comparison-accessibility.js
We should merge and deploy quickly to address #788.  Until we do, the accessibility values for comparison scenarios will be fixed to 5th percentile travel times, no matter what percentile is selected (and despite the fact that the label says median).
This PR also includes clearer guidance on Bundles.  An additional enhancement would be #791
> Percentile and bundle fixes

- lib/actions/analysis/index.js
In the past, travel time percentile could be null, this forces it be set on each single point request.
closes https://github.com/conveyal/analysis-ui/issues/613
> Force travel time percentile to be set when it is null

- lib/components/analysis/map.js
Displaying isochrones has been eating up resources and this should help keep that down.
> Calculate id and style outside of render call to prevent unnecessary re-renders

- lib/components/analysis/regional.js
- lib/containers/regional-analysis-results.js
Load opportunity datasets when needed to show the name in a regional analysis instead of just the
ID.
closes #796
> Fix opportunity dataset name display in a regional analysis

- lib/components/modification/__tests__/__snapshots__/group.js.snap
- lib/components/modification/editor.js
- lib/components/modification/group.js
- lib/components/modification/list.js
- lib/constants/index.js
- lib/utils/modification.js
Will just have a freeform text field and variant editor. Custom types are created with an empty `r5type` parameter that can be used on the R5 side to convert it into corresponding types. This should be useful for testing modifications by updating r5 without needing to update the UI or backend.
TODO:
re #845
> Add custom modification type

- lib/components/flex-container.js
- lib/components/modification/add-trip-pattern.js
- lib/components/transit-mode-selector.js
- lib/constants/index.js
- lib/utils/modification.js
- package.json
- yarn.lock
Defaults new Add Trip Modifications to BUS (same as the R5 default). Old modifications will still not have anything set and get the r5 default. Backend change adding a `transitMode` parameter to the AddTripPattern model is necessary for the changes to work (https://github.com/conveyal/analysis-backend/pull/235).
close #806
> Add a transit mode selector for add trip pattern modifications

- lib/components/analysis/__tests__/__snapshots__/advanced-settings.js.snap
- lib/components/analysis/advanced-settings.js
- lib/components/analysis/egress-mode-selector.js
Disabled if no transit modes are selected
fix #850
> Re-enable bike egress mode selection in the analysis ui

- next.config.js
Removes unused Moment locale files which helps reduce gzipped bundle size by 300kb across all chunks.
> Ignore moment locales by default to reduce bundle sizes

- lib/components/edit-region.js
Event target was not being persisted in the setState closure created by the useState hook for the
region. This change copies that new value from the target before "closing over" it.
fix #909
> fix(region): Fix region bounds editing

- lib/components/modification/__tests__/__snapshots__/timetable.js.snap
- lib/components/modification/phase.js
The upgrade to the latest version of react-select required new props for capturing the selected value and for setting if the component is clearable. The Phasing select's were not updated correctly during the process. This PR:
1. Makes the Phasing Select boxes clearable
2. Fixes the passed values to be the correct ID's when selected.
3. Disables the auto-clearing of non-existing Timetables and instead shows a warning.
4. Refactors the code to be a bit simpler and use hooks.
fix #912 
1. Create an Add Trips modification with two timetables.
2. Phase one timetable to the other timetable and vise-versa.
3. Delete one timetable and ensure that the warning message is now shown for the remaining timetable.
> Fix bug preventing users from selecting phasing options

- lib/components/analysis/__tests__/__snapshots__/profile-request-editor.js.snap
- lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
- lib/modules/r5-version/components/__tests__/__snapshots__/selector.js.snap
- lib/modules/r5-version/components/selector.js
- lib/modules/r5-version/constants.js
- lib/modules/r5-version/selectors.js
When there were no previously used versions of r5 we would display an unnecessary warning saying there was a mismatch. This PR fixes that.
Fixes #914
1. Verify no warning message is shown when no previous analyses have been run or the previous analyses have been run with the recommended version (currently v4.7.0)
2. Verify a warning message is shown when previously run analyses have been run with something other than the currently selected version.
> Fix r5 version warning

- i18n/en.json
- lib/components/modification/__tests__/__snapshots__/adjust-dwell-time.js.snap
- lib/components/modification/__tests__/__snapshots__/adjust-speed.js.snap
- lib/components/modification/__tests__/__snapshots__/reroute.js.snap
- lib/components/modification/adjust-dwell-time.js
- lib/components/modification/adjust-speed.js
- lib/components/modification/editor.js
- lib/components/modification/select-feed-and-routes.js
- lib/components/modification/select-feed-route-and-patterns.js
- lib/components/modifications-map/adjust-speed-layer.js
- lib/components/modifications-map/display.js
When multiple routes are selected, disallow selecting portions of the route displayed as the modification will be applied to the entirety of each route. This also updates the warning messages shown to reflect that.
Fixes #697 
1. Create Adjust Speed modification.
2. Select all routes.
3. Run analysis ensuring the modification was applied for each route in the feed.
4. Repeat for Remove Trips.
> Multiple route warnings

- lib/actions/aggregation-areas.js
- lib/components/analysis/aggregation-area.js
- lib/components/modification/select-feed-and-routes.js
Add's two new field's to the aggregation area form. A checkbox to control whether or not the upload will union all of the features and a text field for setting the attribute name when not unioning.
Fixes #862 
Note: also removes an unused variable that ESLint was warning about. This variable was no longer in use from #917 
1. Upload a shapefile with multiple attributes, leave the union box checked.
2. Upload a shapefile with multiple attributes, uncheck the union box and ensure that new aggregation areas were created for each attribute.
> Add Union option for aggregation areas

- i18n/en.json
- lib/modules/opportunity-datasets/components/upload.js
Adds two checkboxes to the opportunity dataset page, allowing singals to the backend that a csv should be converted to a freeform pointset (see https://github.com/conveyal/r5/pull/529):
We expect two common use cases to be:
1. Calculating accessibility or travel times using discrete points as origins (rather than all points in our web mercator grid)
1. Calculating travel times for known origin-destination pairs.
For the former case, it makes sense to specify latitude, longitude, and id columns in the uploaded shapefile.  For the latter case, each row would have a second latitude/longitude (hence the second checkbox)
As a side note, we're getting closer to having OD = origin/destination (instead of the jargony "opportunity dataset")
Fixes #345 (at least for the UI)
1. On the opportunity …
> Option to process uploaded .csv files into freeform (non-grid) pointsets

- .gitignore
- i18n/en.json
- lib/modules/opportunity-datasets/components/upload.js
Some of the new hidden freeform fields were not sent in the request to the backend. I added them to the form. Also added a "count field" field and changed the names of the paired lat/lon field parameters to latField2 and lonField2 to match the backend.
1. Choose a CSV file to upload as an opportunity dataset.
2. Select "freeform" option and in the red boxed hidden fields that appear, enter a specific field name in the CSV containing counts.
3. On upload, check that two datasets are created: one with (freeform) in the name and the other a matching grid.
4. Re-upload the data without specifying a counts column, but with freeform still selected.
5. Check that two datasets are created: one with (freeform) [COUNT] containing all 1s and the other a matching grid.
> More freeform fields

- lib/auth.js
- next.config.js
- now.json
- now.production.json
Add `AUTH_DISABLED=true` to your `.env.build` to disable auth for local usage.
Recent changes made disabling authentication impossible. When auth is disabled email and accessGroup are both set to `local`. This may cause you to see an empty set of regions.
> Add AUTH_DISABLED config option

- docs/prepare-inputs/upload-opportunity-data.md
This is mostly a reorganization of existing content. My goal was to put the more important information first before trailing off into the necessary specifics of implementation and formatting. Hopefully the example CSV better clarifies how these should be formatted, though most of the requirements for that are still given in the text. 
I removed the note about later LODES data as it seems only 2015 data are available at the moment.
There is also some semantic ambiguity here which these changes don't yet address, as that would involve changes to the UI itself. 
As it is, a "**dataset**" seems to be a numeric (count) attribute associated with a spatial distribution, and a "**dataset source**" essentially just is the spatial distribution or spatial dataset which may have several count …
> Refactoring opportunity dataset docs for clarity

- docs/prepare-inputs/index.md
I've reworked these command line examples for the various OSM tools to make the outputs mostly consistent, using the same coordinates and filters across examples. 
I also reformatted with line breaks so they would fit on the screen rather than breaking the layout of the manual as they do now. 
Regarding the two filter commands, it would be good to verify that these include all possible ways/relations used by r5. I adapted both to the more exclusive osmium command that is here currently.
> Cleaning up OSM command line examples

- lib/with-initial-fetch.js
The loading spinner was no longer being displayed with updated CSS changes. This PR fixes that.
1. Go to a a region.
2. Click on a project. Verify the spinner in the dock is displayed while the page transition is occuring.
> Fix spinner that was no longer being displayed

- lib/components/modification/timetables.js
>  Improve text clarity of Add and Copy timetable buttons

- lib/components/create-region.js
- package.json
This adds a spinner and a message to the Region creation button when clicked to help ensure users that creation is in progress.
We cannot currently show actual progress as the creation endpoint does not return an id to query. 
Fixes #951 
1. Fill in region creation form properly
2. Click "Create Region"
2. Ensure spinner and message show.
> Add region creation message

- lib/components/map/index.js
When the page change is complete we invalidate the map to resize it and redraw it. A lot of this is
done automatically by leaflet, but due to the type of elements we use and due to using a mapbox gl
tile layer we need to do it manually. This adds an additional size invalidation after a delay to wait for all other elements to be drawn.
fix #971
1. Go to a region. Verify the entire map is shown.
2. Without reloading the page, go to a different region. Verify the new region map is shown.
> Fix issue causing half the map not to show

- lib/components/sidebar.js
- pages/_app.js
Fixes #941 
1. Navigate to a project.
2. Click Analysis in the sidebar. 
3. Ensure the project is preselected in the dropdown.
> Fix selected project in Analysis screen

- pages/regions/[regionId]/resources/[resourceId].js
A date format issue was causing resource display to fail (see https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md)
Go to https://analysis-staging-git-fix-resource-page.conveyal.now.sh/regions/5b686a7432b98e600d394981/resources/
Select an uploaded polygon file, ensure it displays.
Compare to failure on [dev](https://analysis-staging.conveyal.now.sh/regions/5b686a7432b98e600d394981/resources)
> Resource page fixes

- lib/selectors/modification-bounds.js
- lib/with-initial-fetch.js
Reroute geometries were excluded from modification bound calculations. This change adds them.
fix #959
1. Create a modification of each type, with a selected route or a added geometry
2. Click the "Fit map to extents" button.
3. Ensure the entire modification is now shown on the map.
> Include reroute in modification bounds

- lib/components/modification/list.js
If a user attempted to create a modification on a slow connection, there is a chance the feeds did
not load yet. Use `get` to prevent an NPE that was being swallowed here. Reported via LogRocket
Discovered here: https://app.logrocket.com/7kj4kr/conveyal-analysis-production/issue/10031519/event/255188332?from=errors
On a slow connection...
1. Go to a region
2. Open a project
3. Before the page can fully load the feeds, create a modification
> Use `get` for finding the feed id

- .github/workflows/nodejs.yml
- next.config.js
- pages/_app.js
1. Cache yarn install (checking if yarn.lock has changed) to speed up the `install` job of the workflow.
2. Add smart default environment variables (only `MAPBOX_ACCESS_TOKEN` is necessary to start now).
3. Only require environment variables to be set on the build step (they aren't needed for other Next.js phases). This will allow us to further separate out the Next.js build step from the cypress test step in the future.
> Cache the yarn install to speed up Github Actions workflow

- lib/components/analysis/__tests__/__snapshots__/title.js.snap
- lib/components/analysis/title.js
- lib/components/modification/__tests__/__snapshots__/editor.js.snap
- lib/components/modification/editor.js
- lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
- styles.css
see #1013
This also re-enables `disableAndDim`
> Fix bug causing long modification names to change layout 

- lib/actions/analysis/index.js
- lib/components/analysis/regional-results-list.js
Perceived speed of single point and regional analyses is drastically reduced due to how we poll. Currently we poll 1 second * the retry count (up to 20 seconds) for single point analyses. For regional we poll every minute. Since we implemented these delays the system has become more robust. This PR changes the single point to delay for one second after the first 10 tries and then increase the delay up to 10 seconds after. It also decreases the regional polling delay to 15 seconds.
1. Ensure no errors while running a single point request
2. Ensure no errors while running a regional analysis
> Decrease polling delays

- pages/regions/[regionId]/opportunities/upload.js
Auth is needed to determine if DEV mode is enabled.
Fixes #1044 
See attached issue
> Ensure auth is provided to the OD upload page

- lib/modules/opportunity-datasets/components/status.js
- styles.css
Currently, the exceptions that bubble up from shapefile uploads look a bit ragged:
This PR adds some CSS to clean that up:
1. Try uploading a problematic shapefile (e.g. the one with topology errors [here](https://www.dropbox.com/sh/zznknms3dcvmlju/AADzJzm5vWKkS9avxgt66JmKa?dl=0))
> Format stack traces shown for shapefile upload errors

- lib/components/modifications-map/gtfs-stop-gridlayer.js
- lib/utils/log-error.js
Valid GTFS stops have a lat/lon. Some invalid GTFS stops are uploaded by our system causing the GTFS stop display to break. This PR handles that error.
Fixes #1052
1. Go to a project that uses the GTFS in the attached issue.
2. Ensure that a reroute modification does not show a white screen while editing geometry.
> Handle error caused by GTFS stops without coordinates

- i18n/en.json
- lib/actions/__tests__/region.js
- lib/actions/region.js
- lib/components/__tests__/__snapshots__/edit-region.js.snap
- lib/components/__tests__/__snapshots__/select-region.js.snap
- lib/components/edit-region.js
- lib/components/error-modal.js
- lib/components/select-region.js
- lib/containers/__tests__/__snapshots__/modification-editor.js.snap
- lib/reducers/__tests__/__snapshots__/region.js.snap
- lib/reducers/region.js
- pages/index.js
- pages/regions/[regionId]/regional/index.js
- pages/regions/create.js
- The culprit here was the `checkLoadStatus` function that was left over from when OSM was uploaded and the region creation took longer than one `fetch`.
- Also fixes a bug that caused opportunity dataset's names not to show
> Delete region locally before sending

- docs/edit-scenario/index.md
- docs/edit-scenario/modifications.md
This PR revises / clarifies a statement about how zero dwell times affect dwell time modifications, and removes a double s typo.
> Small docs fixes: clarify dwell scaling, remove double s

- lib/actions/analysis/regional.js
Fixes a bug introduced in the latest release that always set travel time percentiles for multi-point analyses to 50.
1. Create a multi-point analysis with a percentile of 50 and one with 95.
2. Ensure they have different results.
> Set travel time percentile correctly

- .github/workflows/lint-jest-build.yml
- cypress.json
Since the build takes two minutes or so it should speed up the completion time because this will run in parallel with jest / lint / type check before Cypress runs.
> Split nextjs build from cypress running

- lib/actions/analysis/regional.js
- lib/components/analysis/create-regional.tsx
- lib/components/analysis/index.tsx
- lib/components/analysis/regional-results.tsx
- lib/components/analysis/regional.tsx
- lib/selectors/regional-comparison-cutoff.js
- lib/selectors/regional-comparison-percentile.js
- lib/selectors/regional-display-cutoff.js
- lib/selectors/regional-display-percentile.js
The new regional analysis code assumes the opportunity dataset still exists, but they may have been deleted. This should fix that problem.
1. Successfully load a regional analysis that has had it's opportunity dataset deleted.
With the new regional analyses we only store the ids of the opportunity datasets. We retrieve the names of the datasets from the database. If you delete an opportunity dataset thats used for a new regional analysis, you can load the analysis and select by id, but it's quite confusing if there is no name.
Fix loading and comparing older regional analysis. The way grids are selected would not work for comparison if a regional analysis did not have a cutoffs array or percentiles array. 
1. Compare two old regional analyses and ensure they load.
Creating a regional …
> Fix no opportunity dataset error

- lib/components/analysis/__tests__/__snapshots__/profile-request-editor.js.snap
- lib/components/analysis/profile-request-editor.tsx
- package.json
- pages/_app.tsx
- yarn.lock
It's a very out of date dependency that uses Bootstrap CSS. Most modern browsers implement their own date input. This PR removes the dependency and replaces it with the native date input.
> Remove react-datetime

- cypress/integration/local/opportunities.js
- cypress/support/index.js
It appears that integration tests will fail (sometimes) when importing from external files. The OD test is the only one that was importing and it fails with an odd Cypress related error. This inlines that import and should fix that error.
> Don't import within integration tests

- lib/components/analysis/profile-request-display.tsx
Don't show the bundle or project in the summary view if they have been deleted. IDs are still available in the detailed view.
> (Deploy to production) Handle viewing a regional analysis with deleted bundle or project

- .github/stale.yml
This PR adds a [bot](https://github.com/marketplace/stale) that comments on issues over a year old indicating the issue is "stale" and then closes the issue two weeks later if there is no further activity. It ignores issues with `bug` and `blocking` tags.
With over 100 issues in this repo I would like to do a general "purge". This assists with that.
Important to note, we can always reopen issues!
> Add stale issue bot

- .github/workflows/lint-jest-build.yml
- cypress.json
- cypress/integration/0-regions.js
- cypress/support/index.js
- package.json
- yarn.lock
Turns out we overused the free tier for Cypress. This PR updates Cypress to 5.2 and disables recording (which speeds up the tests in the Github Actions themselves).
> Disable recording to speed up cypress tests

- lib/components/__tests__/panel.js
- lib/components/analysis/mode-selector.tsx
Using distinct styles instead of the button's "active" mode.
> Make modes selected more obvious

- lib/components/editable.tsx
When saving a scenario name or modification name it's possible to see the old name flash for a second. This change waits for the editable component to finish the `onChange` method (which is usually a fetch) before reverting the editable component to the view state.
> Prevent flash of out of date content when saving an Editable

- lib/components/analysis/create-regional.tsx
PR #1287 removed the ability to select a travel time percentile for regional analysis. This PR adds the ability to edit the cutoff and percentile for older versions of r5 in the create regional analysis screen.
> Add inputs for older r5 versions

- .github/dependabot.yml
Too much noise right now. Would still like to get update notifications regularly, just not that often.
> [Dependabot] Change update interval to monthly

- .github/stale.yml
The original tag "wontfix" sounds like an intentional decision/judgement from the developers.
Tagging them "stale" is more objective and descriptive when understanding later why they were closed.
Also updated the automatic comments to be less generic and better match our processes.
> Change stale tag to "stale", update comment text

- cypress/index.d.ts
- cypress/integration/0-regions.ts
- cypress/models/region.ts
- cypress/support/commands.ts
- lib/components/sidebar.tsx
Region settings is not frequently accessed and therefore does not need to be in the sidebar.  This change removes it. The page is still accessible from the gear icon at the top of the "Projects" page.
Fixes #1406
> Remove region settings link from the sidebar

- lib/components/modification/street-form.tsx
Specify version v5.9.0 _or higher_, and make the alert an orange warning instead of a red error
> Update R5 version warning for street modifications

- cypress/integration/modifications/add-trip-pattern.ts
- lib/components/modifications-map/transit-editor/index.tsx
Incorrect `stopIndex` was being passed to `onDragStop`. This adds a test with the examples from #1432 and fixes the problem by using the correct stop index. 
Other changes include using the specific array index for each point type for its key/title.
fixes #1432
> Bugfix: use correct index when dragging stops

- lib/actions/analysis/parse-times-data.ts
- lib/actions/analysis/regional.ts
- lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
- lib/components/analysis/regional-results.tsx
- lib/components/map/regional.js
- lib/selectors/regional-display-grid.ts
- lib/selectors/regional-display-scale.ts
- lib/selectors/regional-grid.ts
- lib/utils/create-grid.ts
- package.json
- types/conveyal.d.ts
- yarn.lock
If the total data values are less than the breaks generated, an ugly uncaught exception will occur. This wraps that exception in a try/catch and shows an error message instead.
I couldn't reproduce the error locally. And therefore was unable to create a Cypress test for this. If someone knows how to reproduce, please let me know.
Addresses #1153
> Wrap ckmeans usage in try/catch to prevent error

- lib/components/sidebar.tsx
- lib/user.ts
- pages/_document.tsx
Add's the snippet from ZenDesk for the chat/support widget. If no "agents" are online (which will be the usual case), it will allow users to directly submit support requests from inside the application.
This PR also identifies all logged in users with the widget so that user's will not have to input their email addresses for us to know who submitted the request/chat.
> Add ZenDesk chat widget

- cypress/integration/clear-data.ts
- lib/components/analysis/create-regional.tsx
- lib/selectors/current-regional-analysis-id.js
- lib/selectors/regional-analyses.js
- lib/user.ts
- lib/utils/auth-fetch.ts
If an error occurs while creating a regional analysis, log it to the console and show it in an `Alert` box. The dispatched fetch was causing errors to be handled in a variety of ways, so I moved it to use a `safeFetch` to handle errors in the same way. (`safeFetch` should never throw an error)
> Show errors in create modal

- lib/actions/analysis/index.ts
Logs entire parsed response, which contains `pathSummaries` when enabled.
Addresses #1391
> Log paths for debugging

- package.json
I noticed slow or highly variable run times when running Cypress tests in the new branch of R5 that runs these tests. In staging and production, we usually give the backend a maximum JVM heap size of many GB. But `yarn start-backend` is using the default max, which is 1/4 of total memory. It's possible that the heap is getting cluttered and the GC thread is using a lot of CPU, slowing down the tests.
The GH Actions documentation at https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners says that Linux runners have 7GB of memory. The JVM heap defaults to 1/4 of that, 1.75 GB. I'm increasing significantly see if tests complete more quickly.
Just observe the Action runs with this change and see if they're faster.
> Increase JVM heap when testing

- cypress/fixtures/regions/nky/hospitals.csv
- cypress/index.d.ts
- cypress/integration/2-opportunities.ts
- cypress/integration/6-analysis.ts
- cypress/integration/example.ts
- cypress/integration/regional/basic.ts
- cypress/integration/regional/origins.ts
- cypress/integration/utils.ts
- cypress/models/freeform-dataset.ts
- cypress/models/model.ts
- cypress/models/region.ts
- cypress/models/regional-analysis.ts
- cypress/models/spatial-data.ts
- cypress/support/analysis.ts
- cypress/support/opportunities.ts
- lib/components/analysis/regional.tsx
- lib/selectors/comparison-analyses.js
- package.json
- yarn.lock
- Add a Cypress test that creates a regional analysis with a freeform origin point set.
- Prevents errors from displaying when viewing a regional analysis that uses a freeform origin point set.
> Add custom origins regional analysis test

- cypress/integration/regional/basic.ts
- lib/components/analysis/__tests__/__snapshots__/profile-request-display.js.snap
- lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
- lib/components/analysis/profile-request-display.tsx
- pages/regions/[regionId]/projects/[projectId]/index.tsx
They were linking to `/regions/[regionId]/projects/[projectId]` which was breaking. This fixes that page from breaking and also changes the link to `/regions/[regionId]/projects/[projectId]/modifications`.
> Fix project back links

- lib/components/analysis/download-menu.tsx
Access to opportunities CSVs that can be downloaded in the single point analysis mode had a `0`th column but the header started at `1`. This fixes that by adding a 0th header.
> Add a 0th column header

- lib/components/analysis/__tests__/__snapshots__/profile-request-editor.js.snap
- lib/components/analysis/profile-request-editor.tsx
The `maxLength` attribute limits the total number of characters allowed to be typed into the input. A min/max number limit only helps with the form validation.
> Limit transfers to 1 character (single digit)

- .github/workflows/lint-jest-build.yml
Recommendations taken from https://github.com/bahmutov/cypress-gh-action-split-install. This should fix the binary installation error we've been seeing in Github Actions.
> Cache Cypress binary, skip initial installation

- cypress/integration/6-analysis.ts
- lib/components/presets.tsx
- lib/db/authenticated-collection.ts
- lib/hooks/use-collection.ts
The original document is returned by default, this change adds the `returnOriginal: false` option to db PUTs in the JavaScript API. 
Fixes #1472
> Return updated document in db PUTs

- pages/_document.tsx
process.browser now prevents the script from being rendered at all. Removing that check.
> Fix Plausible script

- lib/utils/get-stop-near-point.ts
Addresses #1497 in alignment editing. Are we aware of other places where missing stop_lat/stop_lon values will trigger errors?
1. Create an add-trip modification for a bundle with a recent MBTA feed. Ensure the alignment can be drawn successfully, specifically that clicking on the map adds a stop and does not trigger a console error.
> Ignore stops without coordinates

- cypress/integration/0-regions.ts
- lib/components/map/geocoder.tsx
- lib/components/map/index.tsx
- lib/utils/mapbox-search.ts
Additionally, this allows us to put the geocoder manually onto the page to more directly control what occurs on a geocoder select. For example, on the Analysis Page we most likely want the marker location to be updated.
> Refactor geocoder to work without react-select

- lib/constants/index.ts
When we updated the Auth0 libraries last week the logout link changed to `/api/auth/logout` but I forgot to update it.
> Fix the logout link

- lib/components/running-analysis.tsx
Error was introduced when we refactored the `ALink` component. Note: if the file was TypeScript originally it would've caught the error.
fixes #1514
> Fix Regional Analysis Link

- cypress/support/commands.ts
- lib/components/sidebar.tsx
Our tooltip provides a label. The html title tag can be removed which shows up slower. `aria-label` is still there for screen reading (if that would ever be necessary other than for test tools).
closes #1516
> Remove double tool tips

- lib/components/task-list.tsx
- lib/hooks/use-activity.ts
- lib/mocks/tasks.ts
- types/conveyal.d.ts
As discussed recently, we have no guarantee that the server's clock is in sync with the client machine's clock. Especially since we're tracking tasks that may take significantly less than a minute, using absolute times reported by the server risks displaying durations that are negative or start well above zero. 
This PR derives a startTime field known to be accurate on the client machine from relative durations reported on the API. I may be breaking some conventions in the way I did this, feel free to push additional changes. This just serves as an example of the idea.
This PR is relative to`status-reporting` but branches off before the recent merge from `dev`, which seems to have broken a filename selector.
> Clock drift compensation and property name changes

- cypress/fixtures/regions/scratch.json
https://github.com/conveyal/r5/pull/715 adds start/end dates to feed names shown when viewing bundles
> Update Cypress test to reflect new feed naming

- lib/components/error-modal.tsx
We'd prefer copy/pasted text of the stack trace over a screenshot
And better logging should obviate the need for users to send us descriptions.
> Remove screenshot instructions from error modal

- lib/components/banner-alert.tsx
- pages/status.tsx
- Horizontal scroll bar was still appearing after the last attempt to fix it, this change removes the use of `vw` entirely.
- Uses the correct `boxSize` attribute for the logo on the status page (not `size`)
> Fix horizontal scrolling and status page logo

- cypress/integration/1-bundles.ts
- lib/components/edit-bundle.tsx
- lib/hooks/use-collection.ts
The `update` method returns an array since it comes from a `useCollection` method. This change finds the correct bundle from that update and sets it properly.
Additionally, 
- Add tests to Cypress updating the bundle name and feed name.
- Add notification toasts on successful saves and deletions.
fixes #1546
> Fix edit bundle name

- lib/components/modification/editor.tsx
It was noticed on slow connections that the debounce occurred frequently enough to disrupt a normal workflow. This triples the normal auto-save interval while maintaining the save functionality (auto-save on an interval and when leaving the page).
> Increase modification auto-save debounce from 10 to 30 seconds

- .github/workflows/lint-jest-build.yml
- analysis.properties
- pom.xml
This PR grabs the specified version of R5 from Github Packages and runs the Cypress tests against it.
Recently we set up Github Packages, which provides one Maven-style repo per Github repo. This allows our other projects to use development builds of R5 as dependencies without going through an external Maven repo; using the Central repo introduces a lot of extra lag time and effort (artifact signing, slow connections etc.)
Previously we were uploading shadow jars (jar containing all dependencies) on every commit of R5 to a particular bucket on S3. With Github Packages configured, the copies on S3 seem redundant, so we stopped uploading those jars to S3 and this mechanism is now deprecated (used only for fetching old worker versions).
This is now working but turned out to be tricker than …
> Get R5 jar from Github Packages

- lib/db/authenticated-collection.ts
`updatedAt` specifically was accidentally being overwritten with a `number` when updates occurred from the frontend.
> Set updatedAt / createdAt to match r5 models

- lib/components/activity-provider.tsx
- lib/components/api-status-bar.tsx
- lib/utils/safe-fetch.ts
- lib/with-auth.tsx
This PR forces a log out if the Java API responds with a 401 or 403 response. We were experiencing cases where the id token expired at a different rate than the client session. This should help mitigate user's having issues with this.
> When the Java API responds with a 401 or 403, log the user out
