lib/components/modification/group.js

To address https://app.asana.com/0/131658553708053/195111948257994

feat(modifications): Show all modifications in the list.

---

lib/components/analysis/index.js
lib/components/analysis/regional.js
lib/components/analysis/spectrogram.js

Allow configuring the colors in the spectrogram, and fix a sorting bug in the regional analysis.

Spectrogram configurable colors

---

lib/actions/get-feeds-routes-and-stops.js
lib/components/modification/editor.js
lib/containers/__tests__/modification-editor.js
lib/utils/mock-data.js
package.json
yarn.lock

fix(modifications): Correct usages of _update and use an array and ch…eck manually instead of using a

Broken Modification Editing Fixes

---

lib/components/__tests__/__snapshots__/edit-project.js.snap
lib/components/__tests__/__snapshots__/project.js.snap
lib/components/__tests__/__snapshots__/r5-version.js.snap
lib/components/__tests__/__snapshots__/scenario.js.snap
lib/components/__tests__/__snapshots__/variant-editor.js.snap
lib/components/__tests__/edit-project.js
lib/components/application.js
lib/components/modification/__tests__/__snapshots__/group.js.snap
lib/components/modification/__tests__/__snapshots__/list.js.snap
lib/components/modification/__tests__/__snapshots__/title.js.snap
lib/components/modification/__tests__/group.js
lib/components/modification/__tests__/list.js
lib/components/modification/group.js
lib/components/modification/list.js
lib/components/modification/title.js
lib/components/project.js
lib/components/r5-version.js
lib/components/scenario.js
lib/components/variant-editor.js
lib/containers/modifications.js
lib/reducers/scenario.js
lib/styles.css

Addresses these tasks:
https://app.asana.com/0/224643457165985/213926843012349
https://app.asana.com/0/224643457165985/213926844202350
https://app.asana.com/0/224643457165985/215064958686672

Modification changes

---

lib/utils/browsochrones.js

Remove a deprecated field from the profile request.

refactor(browsochrones): remove deprecated profile request field.

---

configurations/default/messages.yml
docs/edit-scenario.md
lib/actions/analysis/__tests__/__snapshots__/index.js.snap
lib/actions/analysis/__tests__/index.js
lib/actions/analysis/index.js
lib/components/analysis/__tests__/__snapshots__/scenario-application-error.js.snap
lib/components/analysis/__tests__/scenario-application-error.js
lib/components/analysis/index.js
lib/components/analysis/scenario-application-error.js
lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
lib/components/modification/__tests__/__snapshots__/editor.js.snap
lib/components/modification/__tests__/__snapshots__/frequency-entry.js.snap
lib/components/modification/__tests__/__snapshots__/timetable-entry.js.snap
lib/components/modification/__tests__/__snapshots__/timetable.js.snap
lib/components/modification/editor.js
lib/components/modification/timetable-entry.js
lib/containers/single-point-analysis.js
lib/reducers/__tests__/__snapshots__/analysis.js.snap
lib/reducers/__tests__/__snapshots__/index.js.snap
lib/reducers/__tests__/analysis.js
lib/reducers/analysis.js
lib/utils/__tests__/timetable.js
lib/utils/browsochrones.js
lib/utils/convert-to-r5-modification/add-trip-pattern.js
lib/utils/convert-to-r5-modification/convert-to-frequency.js
lib/utils/mock-data.js
lib/utils/time.js
lib/utils/timetable.js

Display errors in the UI when there is a backend error.

Error reporting

---

configurations/default/messages.yml
index.html
lib/components/analysis/index.js
lib/components/create-grid.js
lib/containers/single-point-analysis.js
lib/styles.css

Once #217 is merged this can be merged directly to dev

Clean up analysis styling

---

lib/utils/convert-to-r5-modification/convert-to-frequency.js

I'm going to go ahead and merge this in the interests of getting this deployed and working today, but @trevorgerhardt please review _ex post facto_.

fix(r5): Fix convert-to-frequency export by feed-scoping IDs.

---

lib/components/application.js
lib/styles.css

It looks like: <img width="500" alt="screenshot 2017-01-06 00 22 05" src="https://cloud.githubusercontent.com/assets/776780/21688356/86f625f4-d3a7-11e6-937a-e6f02a2bb1d9.png">

Add beta badge

---

lib/containers/__tests__/__snapshots__/application.js.snap

Again, going to merge but leave this here for review in case anyone has any comments.

test(ui): Fix failing snapshot (add `beta` badge)

---

lib/reducers/__tests__/__snapshots__/map-state.js.snap
lib/reducers/map-state.js
lib/utils/auth0.js
package.json
yarn.lock

This will hopefully fix the ambiguous log out error we're having on production. 😕

Fix auth0 logout

---

lib/styles.css

See here: https://bitsofco.de/the-new-system-font-stack/
Makes it appear "native" whatever browser you choose.

Switch to the system font stack for performance

---

lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
lib/components/modification/__tests__/__snapshots__/editor.js.snap
lib/components/modification/__tests__/__snapshots__/group.js.snap
lib/components/modification/__tests__/__snapshots__/list.js.snap
lib/components/modification/__tests__/__snapshots__/timetable.js.snap
lib/components/modification/group.js
lib/components/modification/timetable.js

`chevron-{direction}` to `caret-{direction}`

Switch to carets

---

lib/components/modification/timetable-entry.js

Fix bug that did not allow setting of times in a timetable

---

configurations/default/messages.yml
lib/components/modification/__tests__/__snapshots__/list.js.snap
lib/components/modification/__tests__/list.js
lib/components/modification/list.js

Allow filtering modifications using search text.

Filter modifications

---

lib/containers/report.js

fix(report): add null check to container.

---

lib/components/analysis/histogram.js
lib/components/analysis/spectrogram.js

Fix a few issues with with the use of d3-color.

fix(analyiss): Correct errors in use of d3-color.

---

lib/components/modification/segment-speeds.js
lib/components/report/__tests__/__snapshots__/add-trips.js.snap
lib/components/report/__tests__/__snapshots__/reroute.js.snap
lib/components/report/__tests__/reroute.js
lib/components/report/add-trips.js
lib/components/report/reroute.js
lib/utils/segments.js

Correct segmentSpeeds showing up as NaN (#271).

Fix report speeds

---

lib/__tests__/__snapshots__/routes.js.snap
lib/components/modification/__tests__/__snapshots__/adjust-dwell-time.js.snap
lib/components/modification/__tests__/__snapshots__/editor.js.snap
lib/components/modification/__tests__/editor.js
lib/components/modification/editor.js
lib/containers/modification-editor.js
lib/styles.css
lib/utils/mock-data.js

Fix reroute nesting

---

lib/actions/project.js
lib/components/edit-project.js
lib/containers/edit-project.js

Remove uncreated projects from local store

---

configurations/default/messages.yml
lib/__tests__/__snapshots__/routes.js.snap
lib/components/application.js
lib/containers/__tests__/__snapshots__/application.js.snap
lib/styles.css

feat(application): Add help link to documentation.

---

configurations/default/messages.yml
lib/actions/analysis/index.js
lib/components/analysis/index.js
lib/containers/single-point-analysis.js
lib/reducers/__tests__/__snapshots__/analysis.js.snap
lib/reducers/analysis.js
lib/utils/browsochrones.js

Allow removing time when removing stops. Also add ability to display scenario application warnings.

Remove time when removing stops

---

lib/components/modification/segment-speeds.js

Don't call onchange for certain empty input values

---

lib/actions/analysis/regional.js
lib/utils/browsochrones.js

Make the regional analysis work in Chrome 57.

Grid loading workaround

---

lib/components/__tests__/__snapshots__/buttons.js.snap
lib/components/__tests__/__snapshots__/edit-bundle.js.snap
lib/components/__tests__/__snapshots__/edit-project.js.snap
lib/components/__tests__/__snapshots__/edit-scenario.js.snap
lib/components/__tests__/__snapshots__/import-modifications.js.snap
lib/components/__tests__/__snapshots__/import-shapefile.js.snap
lib/components/__tests__/__snapshots__/select-project.js.snap
lib/components/__tests__/__snapshots__/select-scenario.js.snap
lib/components/__tests__/buttons.js
lib/components/analysis/spectrogram-selector.js
lib/components/buttons.js
lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
lib/components/modification/__tests__/__snapshots__/convert-to-frequency.js.snap
lib/components/modification/__tests__/__snapshots__/edit-alignment.js.snap
lib/components/modification/__tests__/__snapshots__/editor.js.snap
lib/components/modification/__tests__/__snapshots__/frequency-entry.js.snap
lib/components/modification/__tests__/__snapshots__/reroute.js.snap
lib/components/modification/__tests__/__snapshots__/timetable.js.snap
lib/containers/__tests__/__snapshots__/application.js.snap

This fix works, however the main issue is that to toggle a button you now have to click on the text, not the button itself. @trevorgerhardt any thoughts?

fix(buttons): initial pass at making radio buttons work again

---

lib/components/analysis/__tests__/__snapshots__/profile-request-editor.js.snap
lib/components/minutes-seconds.js
lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
lib/components/modification/__tests__/__snapshots__/frequency-entry.js.snap
lib/components/modification/__tests__/__snapshots__/reroute.js.snap
lib/components/modification/__tests__/__snapshots__/timetable-entry.js.snap
lib/components/modification/__tests__/__snapshots__/timetable.js.snap
lib/components/modification/phase.js
lib/components/modification/segment-speeds.js
lib/components/modification/timetable-entry.js
lib/components/time-picker.js
lib/containers/__tests__/__snapshots__/modification-editor.js.snap
lib/utils/time.js

And switch Phasing minutes, Dwell time, and segment speeds to use it.
refs #320

Add mm:ss component

---

lib/actions/modifications.js
lib/components/application.js
lib/components/modification/editor.js
lib/containers/__tests__/__snapshots__/modification-editor.js.snap
lib/containers/modification-editor.js
lib/reducers/network.js
lib/utils/copy-modification.js

Duplicate modification

---

lib/components/analysis/regional.js

fix(regional): fix regional analysis download

---

configurations/default/messages.yml
lib/components/input.js
lib/components/modification/editor.js
lib/components/report/modification.js
lib/containers/__tests__/__snapshots__/modification-editor.js.snap
lib/containers/__tests__/modification-editor.js

feat(modification-editor): add descriptions to modifications.

---

lib/actions/modifications.js
lib/components/__tests__/__snapshots__/import-modifications.js.snap
lib/components/__tests__/import-modifications.js
lib/components/import-modifications.js
lib/utils/copy-modifications.js

Correctly match new ids for copied modification timetables when importing from another scenario. Addresses #402

Fix import modifications

---

lib/components/import-shapefile.js

Pretty simple fix. I'd like to get this deployed on Monday.

fix(import-shapefile): Fix import shapefile component.

---

configurations/default/messages.yml
lib/__tests__/__snapshots__/routes.js.snap
lib/components/report/__tests__/__snapshots__/modification.js.snap
lib/components/report/add-trips.js
lib/components/report/adjust-frequency.js
lib/components/report/index.js
lib/components/report/modification.js
lib/components/report/phase.js
lib/containers/__tests__/__snapshots__/report.js.snap
lib/containers/report.js
lib/selectors/feed-scoped-stops.js
lib/utils/mock-data.js

* Fix printing on chrome by making bootstrap floated elements not floated.
* Add phasing information to reports.
* Add numbers to each modification in reports (basically a page number).

Report improvements

---

lib/actions/analysis/index.js
lib/components/analysis/index.js
lib/components/edit-project.js
lib/components/modification/phase.js
lib/components/r5-version.js
lib/components/scenario-map/reroute-layer.js
lib/containers/single-point-analysis.js
lib/reducers/analysis.js
lib/types.js

Addresses #244, #299, and #422

Backlog bugfixes

---

lib/actions/__tests__/__snapshots__/modifications.js.snap
lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
lib/components/modification/__tests__/__snapshots__/edit-alignment.js.snap
lib/components/modification/__tests__/__snapshots__/reroute.js.snap
lib/components/modification/edit-alignment.js
lib/containers/__tests__/__snapshots__/modification-editor.js.snap
lib/utils/modification.js

Create stops automatically now defaults to false. Bidirectional now defaults to true.

Swap line editing defaults

---

package.json
yarn.lock

See https://github.com/conveyal/jsolines/issues/24 and https://github.com/conveyal/jsolines/pull/37

Smooth isochrones by updating jsolines

---

lib/components/analysis/index.js
lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
lib/containers/single-point-analysis.js

Add the ability to download single point analysis isochrones as GeoJSON. Addresses #344

Download isochrones as GeoJSON for use in GIS

---

lib/actions/analysis/regional.js

Reverting a recent change that I thought also took care of this issue

Fix auth error from s3 when loading a regional analysis grid

---

lib/__tests__/__snapshots__/routes.js.snap
lib/reducers/user.js
lib/routes.js
package.json
yarn.lock

Just add `GOOGLE_ANALYTICS_ID` to your `env.yml` to use.

Add page view and user data tracking ability

---

lib/utils/auth0.js

Safely retrieve the Auth0 token expiration time

---

configurations/default/messages.yml
lib/modules/opportunity-datasets/actions.js
lib/modules/opportunity-datasets/components/__tests__/__snapshots__/list.js.snap
lib/modules/opportunity-datasets/components/list.js

UI changes to address #511.
Depends on https://github.com/conveyal/analysis-backend/pull/78

Grid downloads

---

lib/components/edit-project.js
lib/containers/edit-project.js

Pass the nonce on project save actions to allow saving

---

lib/actions/analysis/index.js
lib/components/analysis/index.js
lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
lib/utils/download-geotiff.js

Add a button that makes a travel time surface request with `Accept: image/tiff` and downloads the results. If a comparison is selected it requests and downloads both.

Download GeoTIFFs

---

lib/__tests__/__snapshots__/reducers.js.snap
lib/components/analysis/__tests__/__snapshots__/profile-request-editor.js.snap
lib/components/import-shapefile.js
lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
lib/modules/r5-version/components/__tests__/__snapshots__/selector.js.snap
lib/modules/r5-version/constants.js

Rename project to projectId

---

lib/components/import-shapefile.js

PR #625 didn't finish the job of fixing #624.  This should.

Fix transit alignment shapefile input

---

lib/actions/modifications.js
lib/components/__tests__/__snapshots__/import-shapefile.js.snap
lib/components/__tests__/import-shapefile.js
lib/components/import-shapefile.js
lib/containers/import-shapefile.js
lib/utils/modification.js

Importing shapefiles and creating modifications from them was broken by changes in how we create
modifications. This updates how we handle all of that.
fixes #633

Fix import shapefile and modification creation

---

.gitignore
lib/__tests__/__snapshots__/routes.js.snap
lib/actions/analysis/index.js
lib/routes.js
lib/utils/auth0.js

Simplifies the log in/out workflow. No longer gets the user info by default since we have everything we need on the login/checkSession requests.

Fix double log out

---

lib/components/map/gridualizer.js
lib/modules/opportunity-datasets/components/__tests__/__snapshots__/dotmap.js.snap
lib/modules/opportunity-datasets/components/dotmap.js

It was causing a major slow down
fixes #609

Don't attempt to draw tiles when data does not exist

---

lib/containers/stacked-percentile-selector.js

Fix scenario names in accessibility bars

---

lib/components/report/__tests__/__snapshots__/add-trips.js.snap
lib/components/report/__tests__/__snapshots__/adjust-dwell-time.js.snap
lib/components/report/__tests__/__snapshots__/adjust-frequency.js.snap
lib/components/report/__tests__/__snapshots__/adjust-speed.js.snap
lib/components/report/__tests__/__snapshots__/mini-map.js.snap
lib/components/report/__tests__/__snapshots__/modification.js.snap
lib/components/report/__tests__/__snapshots__/remove-stops.js.snap
lib/components/report/__tests__/__snapshots__/remove-trips.js.snap
lib/components/report/__tests__/__snapshots__/reroute.js.snap
lib/components/report/mini-map.js
lib/containers/__tests__/__snapshots__/report.js.snap

Remove report map rotation

---

docs/analysis/index.md
docs/edit-scenario/index.md
docs/edit-scenario/modifications.md
docs/glossary.md
docs/index.md
docs/index.rst
docs/learn-more/developers.md
docs/learn-more/faq.md
docs/prepare-inputs/index.md
docs/prepare-inputs/upload-opportunity-data.md

Mostly styling, some corrections

Minor updates to user manual

---

docs/analysis/regional.md

This will make language clearer for users.

Sample documentation change

---

configurations/default/messages.yml
lib/components/analysis/index.js
lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap

Fix label for travel time percentile settings

---

lib/utils/auth0.js

Alert when a user does not have a "group"

---

lib/index.js
package.json
yarn.lock

Polyfill promises

---

configurations/default/messages.yml
lib/components/modification/__tests__/__snapshots__/adjust-dwell-time.js.snap
lib/components/modification/__tests__/__snapshots__/remove-stops.js.snap
lib/components/modification/__tests__/__snapshots__/select-stops.js.snap
lib/components/modification/__tests__/select-stops.js
lib/components/modification/adjust-dwell-time.js
lib/components/modification/remove-stops.js
lib/components/modification/select-stops.js
lib/components/modifications-map/draw-polygon.js
lib/components/modifications-map/stop-select-polygon.js
lib/utils/mock-data.js

- Allows automatic activation of polygon draw tool
- Disables some buttons in stop selection tool
- Adds help text to stop selection
Seeks to resolve #461

Make selection of stops more intuitive

---

configurations/default/messages.yml
lib/components/modification/__tests__/__snapshots__/adjust-speed.js.snap
lib/components/modification/adjust-speed.js
lib/components/modifications-map/__tests__/__snapshots__/hop-select-polygon.js.snap
lib/components/modifications-map/__tests__/__snapshots__/stop-grid-layer.js.snap
lib/components/modifications-map/__tests__/hop-select-polygon.js
lib/components/modifications-map/__tests__/stop-grid-layer.js
lib/components/modifications-map/gtfs-stop-gridlayer.js
lib/components/modifications-map/hop-select-polygon.js
lib/components/modifications-map/index.js
lib/components/modifications-map/transit-editor/index.js
lib/utils/get-stops-from-feeds.js

- Make polygon selection activate automatically
- Show some info text
- Show stops layer while selecting a segment
Fixes #694.
Built on top of #797

Adjust speed improvement

---

lib/actions/__tests__/__snapshots__/modifications.js.snap
lib/actions/__tests__/modifications.js
lib/actions/modifications.js
lib/components/import-modifications.js

Redirect to modifications after importing modifications

---

lib/actions/analysis/index.js
lib/components/analysis/__tests__/title.js
lib/components/analysis/title.js

Also, switch the retry time to double in seconds to handle faster responses.

Set isochrone fetch status from the worker if it exists

---

lib/actions/analysis/index.js

Fixes two problems:
1. Scenario application warnings were not being shown (should be in side panel)
1. Miscellaneous routing errors and AnalysisServerExceptions were not being shown (should be in modal, #820)

Show errors

---

configurations/default/messages.yml
lib/components/modification/__tests__/__snapshots__/reroute.js.snap
lib/components/modification/__tests__/__snapshots__/timetable.js.snap
lib/components/modification/segment-speeds.js
lib/utils/get.js

Clarify default time table dwell time description and make changes to it consistent

---

configurations/default/messages.yml
lib/components/modification/__tests__/editor.js
lib/components/modification/editor.js
lib/containers/__tests__/__snapshots__/modification-editor.js.snap

This will also make it simple to implement 100% custom modifications in the future.

Add ability to edit modification json directly

---

lib/actions/region.js

Omit comparisonVariant from bookmark props when saving to prevent error

---

lib/__tests__/__snapshots__/routes.js.snap
lib/routes.js
package.json
yarn.lock

See https://github.com/conveyal/analysis-backend/pull/210 for more info

Remove react-ga in favor of using in script tag

---

lib/utils/markers.js

Handle case with less than two coordinates being passed to directional markers

---

lib/components/create-region.js
lib/components/map/edit-bounds.js
lib/utils/reproject-coordinates.js

Don't allow invalid bounds in during region creation.

---

lib/__tests__/__snapshots__/reducers.js.snap
lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
lib/modules/opportunity-datasets/actions.js
lib/modules/opportunity-datasets/components/__tests__/__snapshots__/upload.js.snap
lib/modules/opportunity-datasets/components/upload.js
lib/modules/r5-version/components/__tests__/__snapshots__/selector.js.snap

Region ids were not being passed correctly when checking for a status, causing a request to be made to an undefined region. This change fixes that error.
Upload a new opportunity dataset and verify the status messages are correctly displayed.
fix #908

Fix opportunity dataset upload status

---

lib/modules/opportunity-datasets/components/upload.js

Remove freeform pointset upload options until the backend changes are finalized.
1. Ensure freeform pointset options no longer exist.
2. Ensure OD upload still works.

 Remove freeform pointset options 

---

pages/status.js

Show version information on the status page. Just prints the JSON supplied by the backend.

Show server version information

---

lib/auth.js
next.config.js
now.json
now.production.json
pages/_app.js
public/static/styles.css
static/empty.txt

Show them if logged in as admin. Add a `.DEV` CSS class around features you do not want to display.
Also displays a thin red border at the top to indicate that an admin is logged in.

Hide features marked with .DEV

---

lib/modules/opportunity-datasets/components/upload.js

Implemented in #922, removed in #924, now showing only in dev mode

Re-enable freeform upload

---

i18n/en.json
pages/regions/[regionId]/resources/upload.js

Add geojson to allowed resource file types

---

lib/components/analysis/__tests__/__snapshots__/advanced-settings.js.snap
lib/components/analysis/advanced-settings.js

Set spellcheck='false' to disable squiggly lines

---

lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
lib/components/modification/__tests__/__snapshots__/frequency-entry.js.snap
lib/components/modification/__tests__/__snapshots__/timetable-entry.js.snap
lib/components/modification/__tests__/__snapshots__/timetable.js.snap
lib/components/modification/__tests__/timetable-entry.js
lib/components/modification/__tests__/timetable.js
lib/components/modification/add-trip-pattern.js
lib/components/modification/convert-to-frequency.js
lib/components/modification/frequency-entry.js
lib/components/modification/phase.js
lib/components/modification/timetable-entry.js
lib/components/modification/timetable.js
lib/components/modification/timetables.js
lib/containers/add-trip-pattern.js
lib/containers/convert-to-frequency.js
lib/selectors/all-phase-from-timetable-stops.js

Check to see if the timetable exists before accessing the properties. This prevents a white screen
of death.
fix #961
See #961

Allow changing selected phase from timetable without crashing

---

pages/regions/[regionId]/analysis.js

Clear warnings and errors on page load

---

lib/components/edit-region.js

Update region after saving to ensure latest nonce is used

---

lib/selectors/modification-bounds.js
pages/_app.js
styles.css

Prevent overscroll in full screen mode

---

lib/selectors/regional-comparison-cutoff.js
lib/selectors/regional-comparison-percentile.js
lib/selectors/regional-display-cutoff.js
lib/selectors/regional-display-percentile.js

1. View a completed regional analysis that is not multi cutoff.

Fix display when viewing non-multicutoff

---

lib/__tests__/__snapshots__/reducers.js.snap
lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
lib/modules/r5-version/components/__tests__/__snapshots__/selector.js.snap
lib/modules/r5-version/constants.js

Update recommended r5 version

---

lib/components/modification/select-feed-and-routes.js

Don't try to read routes if feed not selected

---

i18n/en.json
lib/auth.js
lib/components/error-modal.js
lib/components/modifications-map/gtfs-stop-gridlayer.js
lib/components/sidebar.js
lib/logrocket.js
lib/reducers.js
lib/utils/log-error.js
next.config.js
pages/_app.js
pages/admin/debug.js

Handle errors in `_app` using a React Error Boundary and show them in the error modal.
fixes #1036
Go to https://analysis-staging-git-fix-wsod.conveyal.now.sh/admin/debug to see the new error modal and test some errors

Fix Handling Errors in _app

---

docs/prepare-inputs/index.md

See discussion in https://github.com/conveyal/r5/issues/568

User manual: add note on exact times

---

cypress/integration/local/bundles.js
cypress/integration/local/regions.js
cypress/support/commands.js

Updating the scratch tests for the new bundle page.

Cypress bundle changes

---

lib/components/analysis/__tests__/__snapshots__/advanced-settings.js.snap
lib/components/analysis/__tests__/advanced-settings.js
lib/components/analysis/advanced-settings.js
lib/components/analysis/index.js
lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap

Add a selector in advanced settings for choosing the maximum traffic stress level allowed.
Fixes #1087 
1. Run a single point analysis while selecting the traffic stress level

Add bike traffic stress selector

---

lib/actions/analysis/regional.js

Patch to fix travel time percentile selection for regional analyses

Production Deployment, Select travel time percentile correctly

---

pages/changelog/20200803.mdx

This change belonged in #1160, but I didn't finish it in time.

Changelog update

---

lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
lib/components/analysis/regional-results.tsx

closes https://github.com/conveyal/analysis-ui/issues/1182

Add regional analysis name to legend

---

lib/components/analysis/create-regional.tsx

Disable close on overlay for regional analysis creation

---

lib/hooks/use-error-handling-toast.ts

This change tracks if an error toast with the same title/description is already open and if it is, it will not show it again. 
closes #1266

Only display unique error toasts

---

lib/components/__tests__/__snapshots__/edit-bundle.js.snap
lib/components/__tests__/__snapshots__/import-modifications.js.snap
lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
lib/components/modification/__tests__/__snapshots__/adjust-speed.js.snap
lib/components/modification/__tests__/__snapshots__/reroute.js.snap
lib/components/modification/__tests__/__snapshots__/select-feed-and-routes.js.snap
lib/components/modification/__tests__/__snapshots__/select-feed-route-and-patterns.js.snap
lib/components/modification/__tests__/__snapshots__/select-patterns.js.snap
lib/components/modification/__tests__/__snapshots__/timetable-entry.js.snap
lib/components/modification/__tests__/__snapshots__/timetable.js.snap
lib/components/select.tsx
lib/modules/opportunity-datasets/components/__tests__/__snapshots__/list.js.snap
lib/modules/opportunity-datasets/components/__tests__/__snapshots__/selector.js.snap
lib/modules/r5-version/components/__tests__/__snapshots__/selector.js.snap

Add a zIndex to the Select dropdown to fix #1278

Select dropdown z

---

lib/components/analysis/results-sliders.tsx

Remove regional text from percentile slider

---

.github/dependabot.yml
.github/stale.yml

We made configuration changes directly to master and a direct update is failing so this PR syncs those changes from master to the dev branch.

Sync with master

---

cypress/index.d.ts
cypress/integration/2-opportunities.ts
cypress/integration/clear-data.ts
cypress/models/opportunity-data.ts
cypress/support/opportunities.ts
lib/components/confirm-button.tsx
lib/components/editable.tsx
lib/modules/opportunity-datasets/components/__tests__/__snapshots__/list.js.snap
lib/modules/opportunity-datasets/components/edit.tsx
lib/modules/opportunity-datasets/components/list.tsx

Show total opportunities, created by, and created at on opportunity edit page.
closes #1125

Show metadata on opportunity page

---

lib/components/map/destination-travel-time-distribution.tsx

In order to enable path results.
After running an analysis a circle marker appears under your mouse on the map that will show you a travel time distribution to that point. If you "lock" the marker in place by clicking on the map the currently displayed toLat/toLon will be added to the analysis request.
Addresses #1391

Add toLat/toLon to the request

---

.github/.kodiak.toml

Remove dependabot from update.always

---

cypress/integration/modifications/add-trip-pattern.ts
lib/components/modifications-map/transit-editor/index.tsx

Alignment editing bugfix (to dev)

---

cypress/integration/2-opportunities.ts
cypress/support/opportunities.ts
i18n/en.json

In upload status messages, "features" should be "layers"

OD upload status

---

.github/workflows/lint-jest-build.yml

Add `pull_request` to event types to enable actions to run on PR's from a forked version of the repository.

Add pull_request to on:

---

cypress/integration/clear-data.ts
lib/components/map/destination-travel-time-distribution.tsx

Fix destination lock

---

cypress/integration/2-opportunities.ts
cypress/integration/6-analysis.ts
cypress/models/spatial-data.ts
cypress/support/analysis.ts
cypress/support/opportunities.ts
i18n/en.json
lib/components/analysis/create-regional.tsx
lib/components/analysis/title.tsx
lib/modules/opportunity-datasets/components/__tests__/__snapshots__/list.js.snap
lib/modules/opportunity-datasets/components/__tests__/__snapshots__/upload.js.snap
lib/modules/opportunity-datasets/components/edit.tsx
lib/modules/opportunity-datasets/components/list.tsx
lib/modules/opportunity-datasets/components/status.tsx
lib/modules/opportunity-datasets/components/upload.tsx

Follow-up to #1463, should fix #988

Spatial dataset labels

---

lib/components/analysis/profile-request-display.tsx

Show falsy values in profile request display

---

pages/_document.tsx

This contains one change, fixing the plausible script.

RELEASE: Fix plausible script

---

lib/utils/get-stop-near-point.ts

Duplicate of #1498, for merge to main and deployment to production

Ignore stops without coordinates

---

lib/components/analysis/__tests__/__snapshots__/legend.js.snap
lib/components/analysis/__tests__/__snapshots__/profile-request-display.js.snap
lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
lib/components/analysis/legend.tsx
lib/components/analysis/profile-request-display.tsx
lib/components/analysis/regional-results.tsx
lib/components/analysis/regional.tsx

The download button was missing an icon and left shifted after the Chakra v1 updates. This PR fixes that and updates a few other regional analysis components to use the proper color mode.

Fix download button

---

pages/index.tsx

Fixes flash of unlogged in content

Add `withAuth` back to the home page

---

cypress/integration/6-analysis.ts
i18n/en.json
lib/components/analysis/__tests__/__snapshots__/title.js.snap
lib/components/analysis/title.tsx

These wording tweaks are intended to describe the state of the interface more consistently, and provide clearer guidance on what the user should do (e.g. click "Fetch results")

Update analysis status messages

---

lib/components/analysis/create-regional.tsx
lib/components/analysis/download-menu.tsx
lib/components/analysis/results-sliders.tsx
lib/components/analysis/single-point-settings.tsx
lib/components/map/index.tsx

- Allow setting the cutoff to 0 (fixes an issue that prevented the graph from updating)
- Move props to prevent needless updates when the cutoff changes.

Cutoff Slider Updates

---

cypress/integration/1-bundles.ts
cypress/support/bundle.ts
lib/components/__tests__/__snapshots__/edit-bundle.js.snap
lib/components/create-bundle.tsx
lib/components/create-project.tsx
lib/components/edit-bundle.tsx
lib/components/task-list.tsx
next.config.js
package.json
pages/regions/[regionId]/bundles/[bundleId].tsx
yarn.lock

Bundle updates

---

lib/components/project-title.tsx
pages/regions/[regionId]/projects/[projectId]/import-modifications.tsx

Fixes #1545 
1. Create a new project
2. Immediately click "Import Modifications" and verify that it loads without errors.

Add null checks in project-title while project is loading

---

i18n/en.json
lib/actions/resources.js
lib/components/select-resource.js
lib/components/task-list.tsx
lib/constants/index.ts
pages/regions/[regionId]/resources/[resourceId].js
pages/regions/[regionId]/resources/upload.tsx
types/conveyal.d.ts

Repurposes the stale Resources page to develop/test the new spatial dataset upload endpoints (in conveyal/r5#732)
Supersedes #1575

Spatial resource prototyping
